"use client";
import {useMemo,useState} from "react";
import {createClient} from "../../../lib/supabase/client";

type Product={id:string;name:string;price:number;cost:number|null;stock:number;category:string|null;description:string|null;image_url:string|null;video_url:string|null;active:boolean;created_at:string;updated_at:string};
const CATEGORIES=["Moda femenina","Herramientas","Electrónica","Hogar","Belleza","Salud","Ofertas","Otros"];
const normalizeCategory=(value:string|null|undefined)=>value==="Electro"?"Electrónica":value==="Ropa"?"Moda femenina":value||"Otros";

export function ProductManager({initialProducts}:{initialProducts:Product[]}){
 const [products,setProducts]=useState(initialProducts); const [q,setQ]=useState(""); const [filter,setFilter]=useState("todos"); const [editing,setEditing]=useState<Product|null>(null); const [busy,setBusy]=useState(false); const [msg,setMsg]=useState("");
 const shown=useMemo(()=>products.filter(p=>{const text=`${p.name} ${normalizeCategory(p.category)}`.toLowerCase(); const ok=text.includes(q.toLowerCase()); const st=filter==="todos"|| (filter==="activos"&&p.active)||(filter==="inactivos"&&!p.active)||(filter==="bajo"&&p.stock<=5); return ok&&st}),[products,q,filter]);
 async function toggle(p:Product){setBusy(true);setMsg("");try{const s=createClient();const {error}=await s.from("products").update({active:!p.active,updated_at:new Date().toISOString()}).eq("id",p.id);if(error)throw error;setProducts(x=>x.map(a=>a.id===p.id?{...a,active:!p.active}:a));}catch(e:any){setMsg("❌ "+(e?.message||"No se pudo actualizar"))}finally{setBusy(false)}}
 async function remove(p:Product){if(!confirm(`¿Eliminar “${p.name}”? Esta acción no se puede deshacer.`))return;setBusy(true);setMsg("");try{const s=createClient();const {error}=await s.from("products").delete().eq("id",p.id);if(error)throw error;setProducts(x=>x.filter(a=>a.id!==p.id));if(editing?.id===p.id)setEditing(null);}catch(e:any){setMsg("❌ "+(e?.message||"No se pudo eliminar"))}finally{setBusy(false)}}
 async function save(p:Product){setBusy(true);setMsg("");try{const s=createClient(); const payload={name:String(p.name||"").trim(),price:Number(p.price)||0,cost:Number(p.cost)||0,stock:Math.max(0,Math.floor(Number(p.stock)||0)),category:normalizeCategory(p.category),description:p.description||null,image_url:p.image_url||null,video_url:p.video_url||null,active:!!p.active,updated_at:new Date().toISOString()};if(!payload.name)throw new Error("El nombre del producto es obligatorio.");const {data,error}=await s.from("products").update(payload).eq("id",p.id).select().single();if(error)throw error;if(!data)throw new Error("No se encontró el producto para actualizar. Verifica los permisos de administrador.");setProducts(x=>x.map(a=>a.id===p.id?{...a,...data}:a));setEditing(null);setMsg("✅ Producto actualizado correctamente.");}catch(e:any){setMsg("❌ "+(e?.message||"No se pudo guardar"))}finally{setBusy(false)}}
 return <>
  <div className="panel product-toolbar"><div className="twocol"><label>Buscar producto<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Nombre o categoría"/></label><label>Filtrar<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="todos">Todos</option><option value="activos">Activos</option><option value="inactivos">Inactivos</option><option value="bajo">Stock bajo (≤ 5)</option></select></label></div><p className="muted">{shown.length} producto(s) mostrado(s) · {products.filter(p=>p.active).length} activo(s).</p></div>
  {msg&&<div className="panel" role="status">{msg}</div>}
  <div className="admin-products">{shown.map(p=><article className="panel admin-product" key={p.id}>
    <div className="admin-product-media" style={{width:150,height:150,maxWidth:"100%",overflow:"hidden",borderRadius:14,display:"flex",alignItems:"center",justifyContent:"center",background:"#eee5e5"}}>{p.image_url?<img src={p.image_url} alt={p.name} style={{width:"100%",height:"100%",objectFit:"contain",display:"block",padding:8}}/>:<b>DF</b>}</div>
    <div className="admin-product-main"><div className="admin-product-top"><div><small>{normalizeCategory(p.category)}</small><h2>{p.name}</h2></div><span className={p.active?"status active":"status"}>{p.active?"Activo":"Inactivo"}</span></div><div className="admin-product-data"><div><span>Precio</span><b>₲ {Number(p.price).toLocaleString("es-PY")}</b></div><div><span>Costo</span><b>₲ {Number(p.cost||0).toLocaleString("es-PY")}</b></div><div><span>Stock</span><b className={p.stock<=5?"low-stock":""}>{p.stock}</b></div></div><div className="actions"><button type="button" className="btn" disabled={busy} onClick={()=>{setMsg("");setEditing({...p,category:normalizeCategory(p.category)});}}>Editar</button><button type="button" className="btn secondary" disabled={busy} onClick={()=>toggle(p)}>{p.active?"Desactivar":"Activar"}</button><button type="button" className="linkbtn danger" disabled={busy} onClick={()=>remove(p)}>Eliminar</button></div></div>
  </article>)}</div>
  {!shown.length&&<div className="empty">No encontramos productos con ese filtro.</div>}
  {editing&&<EditProduct product={editing} busy={busy} onCancel={()=>setEditing(null)} onSave={save}/>} 
 </>;
}
function EditProduct({product,busy,onCancel,onSave}:{product:Product;busy:boolean;onCancel:()=>void;onSave:(p:Product)=>void}){
 const [p,setP]=useState({name:String(product.name??""),price:String(product.price??""),cost:String(product.cost??""),stock:String(product.stock??""),category:normalizeCategory(product.category),description:product.description||"",image_url:product.image_url||"",video_url:product.video_url||"",active:product.active});
 const set=(k:keyof typeof p,v:string|boolean)=>setP(x=>({...x,[k]:v}));
 const submit=()=>onSave({...product,name:p.name,price:Number(p.price)||0,cost:Number(p.cost)||0,stock:Math.max(0,Math.floor(Number(p.stock)||0)),category:normalizeCategory(p.category),description:p.description,image_url:p.image_url,video_url:p.video_url,active:p.active});
 return <div className="modal-backdrop" role="dialog" aria-modal="true" style={{position:"fixed",inset:0,zIndex:9999,background:"rgba(0,0,0,.58)",display:"flex",alignItems:"center",justifyContent:"center",padding:16,overflowY:"auto"}} onMouseDown={e=>{if(e.target===e.currentTarget)onCancel();}}><div className="panel edit-modal" style={{width:"min(680px,100%)",maxHeight:"calc(100vh - 32px)",overflowY:"auto",margin:0,background:"#fff",position:"relative"}}><div className="title"><div><small>EDITAR PRODUCTO</small><h2>{p.name||"Producto"}</h2></div><button type="button" className="linkbtn" onClick={onCancel}>Cerrar ✕</button></div><label>Nombre<input autoFocus value={p.name} onChange={e=>set("name",e.target.value)}/></label><div className="twocol"><label>Precio<input type="number" min="0" value={p.price} onChange={e=>set("price",e.target.value)}/></label><label>Costo<input type="number" min="0" value={p.cost} onChange={e=>set("cost",e.target.value)}/></label></div><div className="twocol"><label>Disponibilidad / Stock<input type="text" inputMode="numeric" pattern="[0-9]*" value={p.stock} onChange={e=>set("stock",e.target.value.replace(/[^0-9]/g,""))} placeholder="0"/></label><label>Categoría<select value={p.category} onChange={e=>set("category",e.target.value)}>{CATEGORIES.map(category=><option key={category} value={category}>{category}</option>)}</select></label></div><label>Descripción<textarea value={p.description} onChange={e=>set("description",e.target.value)}/></label><label>URL de foto de portada<input value={p.image_url} onChange={e=>set("image_url",e.target.value)} placeholder="https://..."/></label><label>URL de video<input value={p.video_url} onChange={e=>set("video_url",e.target.value)} placeholder="https://..."/></label><label className="check"><input type="checkbox" checked={p.active} onChange={e=>set("active",e.target.checked)}/> Producto activo</label><div className="actions"><button type="button" className="btn" disabled={busy} onClick={submit}>{busy?"Guardando...":"Guardar cambios"}</button><button type="button" className="btn secondary" disabled={busy} onClick={onCancel}>Cancelar</button></div></div></div>
}
