"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {normalizePyWhatsapp} from "../../../lib/phone-py";

const CONTACT_WHATSAPP="595974719210";
const DEFAULT_MESSAGE="¡Hola, {nombre}! 😊 ¿Cómo estás?\nNotamos que casi terminaste tu compra en DF Store PY. 🛍️\nSi tuviste algún inconveniente o necesitás ayuda para finalizar el pedido, escribinos. ¡Estamos para ayudarte! 💕";
type Stage={label:string;value:number};
type Draft={session:string;full_name:string|null;whatsapp:string|null;email:string|null;department:string|null;city:string|null;neighborhood:string|null;address:string|null;delivery_type:string|null;payment_method:string|null;updated_at:string};
const timeAgo=(iso:string)=>{const mins=Math.max(1,Math.round((Date.now()-new Date(iso).getTime())/60000));if(mins<60)return `hace ${mins} min`;const hs=Math.round(mins/60);if(hs<24)return `hace ${hs} h`;return `hace ${Math.round(hs/24)} d`;};
export default function Embudo(){
 const [loading,setLoading]=useState(true);const [msg,setMsg]=useState("");const [stages,setStages]=useState<Stage[]>([]);const [drafts,setDrafts]=useState<Draft[]>([]);const [contactNumber,setContactNumber]=useState(CONTACT_WHATSAPP);const [messageTemplate,setMessageTemplate]=useState(DEFAULT_MESSAGE);const [savingSettings,setSavingSettings]=useState(false);
 async function load(){setLoading(true);setMsg("");try{const r=await fetch("/api/admin/embudo",{method:"GET",cache:"no-store",credentials:"include"});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);setStages(data.stages||[]);setDrafts(data.drafts||[]);setContactNumber(data.settings?.whatsapp||CONTACT_WHATSAPP);setMessageTemplate(data.settings?.abandoned_checkout_message||DEFAULT_MESSAGE);}catch(e:any){setMsg(e?.message||"No se pudo cargar el embudo.");}finally{setLoading(false);}}
 useEffect(()=>{load()},[]);
 async function saveSettings(){setSavingSettings(true);setMsg("");try{const r=await fetch("/api/admin/embudo",{method:"PATCH",headers:{"Content-Type":"application/json"},credentials:"include",body:JSON.stringify({whatsapp:contactNumber,abandoned_checkout_message:messageTemplate})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);setContactNumber(data.whatsapp||contactNumber);setMessageTemplate(data.abandoned_checkout_message||messageTemplate);setMsg("✅ Número y mensaje guardados.");}catch(e:any){setMsg(e?.message||"No se pudieron guardar los ajustes.");}finally{setSavingSettings(false);}}
 async function discard(session:string){if(!window.confirm("¿Descartar este checkout abandonado de la lista?"))return;setMsg("");try{const r=await fetch("/api/admin/embudo",{method:"DELETE",headers:{"Content-Type":"application/json"},credentials:"include",body:JSON.stringify({session})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);setDrafts(v=>v.filter(d=>d.session!==session));}catch(e:any){setMsg(e?.message||"No se pudo descartar el checkout.");}}
 const total=stages[0]?.value||0;const buildMessage=(name:string|null)=>messageTemplate.replaceAll("{nombre}",name||"cliente");const buildWhatsAppLink=(phone:string|null,name:string|null)=>{const normalized=normalizePyWhatsapp(phone||"");const text=encodeURIComponent(buildMessage(name));if(typeof navigator!=="undefined"&&/Android/i.test(navigator.userAgent))return `intent://send?phone=${normalized}&text=${text}#Intent;scheme=whatsapp;package=com.whatsapp.w4b;end`;return `https://wa.me/${normalized}?text=${text}`;};
 return <section><div className="title"><div><small>ADMINISTRADOR</small><h1>Embudo de ventas</h1></div><Link href="/admin">← Admin</Link></div>{msg&&<div className="panel">⚠️ {msg}</div>}
 <div className="panel"><h2>Recorrido del cliente</h2><p className="muted">Datos reales de tu tienda, calculados desde Supabase.</p>{loading?<p className="muted">Cargando...</p>:<div className="funnel-grid">{stages.map(st=>{const pct=total?Math.round((st.value/total)*100):0;return <div className="funnel-card" key={st.label}><b>{st.value}</b><span>{st.label}</span><small>{pct}%</small><div className="funnel-bar"><i style={{width:`${Math.min(100,pct)}%`}}/></div></div>})}</div>}<button className="btn secondary" onClick={load} disabled={loading}>{loading?"Actualizando...":"Actualizar"}</button></div>
 <div className="panel"><h2>Contacto de checkouts abandonados</h2><p className="muted">El enlace abre el chat del cliente usando WhatsApp Business, donde debe estar registrada la línea de atención configurada.</p><label>Número de WhatsApp de atención<input value={contactNumber} onChange={e=>setContactNumber(e.target.value)} placeholder="0974 719 210" inputMode="tel"/><small>Configurado: {contactNumber}. Este número identifica la línea de atención de tu negocio.</small></label><label>Mensaje editable<small>Usá <b>{"{nombre}"}</b> para insertar automáticamente el nombre del cliente.</small><textarea rows={6} value={messageTemplate} onChange={e=>setMessageTemplate(e.target.value)}/></label><button className="btn" onClick={saveSettings} disabled={savingSettings}>{savingSettings?"Guardando...":"Guardar número y mensaje"}</button></div>
 <div className="panel"><h2>Checkouts abandonados</h2><p className="muted">Clientes que empezaron a completar sus datos en el checkout pero no llegaron a confirmar el pedido. Podés contactarlos por WhatsApp para ayudarlos a terminar la compra.</p>{loading?<p className="muted">Cargando...</p>:!drafts.length?<div className="empty"><h3>No hay checkouts abandonados</h3><p>Cuando alguien empiece el checkout sin terminarlo, va a aparecer acá.</p></div>:<div className="payment-list">{drafts.map(d=><div className="panel payment-row" key={d.session}><div><b>{d.full_name||"Sin nombre"}</b> · {timeAgo(d.updated_at)}<br/>{d.whatsapp&&<>📱 {d.whatsapp}<br/></>}{(d.department||d.city)&&<span className="muted">{[d.city,d.department].filter(Boolean).join(", ")}<br/></span>}{d.address&&<span className="muted">{d.address}<br/></span>}{d.delivery_type&&<span className="muted">{d.delivery_type}{d.payment_method?` · ${d.payment_method}`:""}</span>}</div><div className="actions">{d.whatsapp&&<a className="btn secondary" target="_blank" rel="noreferrer" href={buildWhatsAppLink(d.whatsapp,d.full_name)}>Contactar por WhatsApp Business</a>}<button className="link-btn danger" onClick={()=>discard(d.session)}>Descartar</button></div></div>)}</div>}</div></section>;
}