"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {createClient} from "../../../lib/supabase/browser";
const money=(n:number)=>`₲ ${Number(n||0).toLocaleString("es-PY")}`;
export default function Reportes(){
 const [orders,setOrders]=useState<any[]>([]),[items,setItems]=useState<any[]>([]),[products,setProducts]=useState<any[]>([]),[loading,setLoading]=useState(true),[msg,setMsg]=useState("");
 useEffect(()=>{(async()=>{const s=createClient();const [a,b,c]=await Promise.all([s.from("orders").select("id,status,total,subtotal,delivery_fee,payment_verified,created_at"),s.from("order_items").select("product_name,quantity,subtotal,order_id"),s.from("products").select("id,name,stock,active,price,cost")]); if(a.error||b.error||c.error)setMsg(a.error?.message||b.error?.message||c.error?.message||"Error"); else {setOrders(a.data||[]);setItems(b.data||[]);setProducts(c.data||[])}setLoading(false)})()},[]);
 const completed=orders.filter(o=>o.status!=="cancelado"), sales=completed.reduce((s,o)=>s+Number(o.subtotal||0),0), delivery=completed.reduce((s,o)=>s+Number(o.delivery_fee||0),0), costs=items.reduce((s,i)=>s+Number(i.subtotal||0)*(Number(products.find(p=>p.name===i.product_name)?.cost||0)/Math.max(1,Number(products.find(p=>p.name===i.product_name)?.price||1))),0);
 const low=products.filter(p=>p.active&&Number(p.stock)<=5).sort((a,b)=>a.stock-b.stock); const top=Object.values(items.reduce((a:any,i:any)=>{a[i.product_name]=(a[i.product_name]||0)+Number(i.quantity||0);return a},{})).length;
 const counts=orders.reduce((a:any,o:any)=>(a[o.status]=(a[o.status]||0)+1,a),{});
 return <section><div className="title"><div><small>ADMINISTRADOR</small><h1>Reportes</h1></div><Link href="/admin">← Admin</Link></div>{loading?<div className="panel">Cargando reportes...</div>:<><div className="adminstats"><div><b>Ventas</b><strong>{money(sales)}</strong></div><div><b>Delivery cobrado</b><strong>{money(delivery)}</strong></div><div><b>Costos estimados</b><strong>{money(costs)}</strong></div><div><b>Pedidos</b><strong>{orders.length}</strong></div></div><div className="formgrid"><div className="panel"><h2>Estado de pedidos</h2>{Object.entries(counts).map(([k,v])=><div className="checkout-total" key={k}><span>{k}</span><strong>{String(v)}</strong></div>)}{!orders.length&&<p className="muted">Todavía no hay pedidos.</p>}</div><div className="panel"><h2>Stock bajo</h2>{low.length?low.map(p=><div className="checkout-total" key={p.id}><span>{p.name}</span><strong>{p.stock}</strong></div>):<p className="muted">No hay productos con stock de 5 o menos.</p>}</div></div><div className="panel"><h2>Resumen</h2><p>Pedidos no cancelados: <b>{completed.length}</b></p><p>Pagos pendientes de verificación: <b>{completed.filter(o=>o.payment_method!=="Pago al recibir"&&!o.payment_verified).length}</b></p><p>Unidades vendidas registradas: <b>{items.reduce((s,i)=>s+Number(i.quantity||0),0)}</b></p><p>Productos activos: <b>{products.filter(p=>p.active).length}</b></p>{msg&&<p>⚠️ {msg}</p>}</div></>}</section>;
}
