import { withSupabase } from "npm:@supabase/server@^1";
const GRAPH_VERSION="v26.0"; const ALLOWED_EVENTS=new Set(["PageView","ViewContent","AddToCart","InitiateCheckout","Purchase"]);
const json=(data:unknown,status=200)=>Response.json(data,{status,headers:{"Cache-Control":"no-store"}});
async function getSecret(admin:any,name:string){const {data,error}=await admin.rpc("get_meta_runtime_secret",{p_name:name});if(error)throw new Error(`secret_error:${name}`);return String(data||"").trim();}
function account(v:unknown){return String(v||"").replace(/^act_/ ,"").replace(/[^0-9]/g,"");}
async function sendCapi(admin:any,body:any){
 const eventName=String(body?.event_name||"");const eventId=String(body?.event_id||"").trim();if(!ALLOWED_EVENTS.has(eventName)||eventId.length<8||eventId.length>128)return json({status:"invalid_event"},400);
 const {data:s,error}=await admin.from("store_settings").select("meta_pixel_id").eq("id",1).maybeSingle();if(error)return json({status:"config_error"},500);
 const pixelId=String(s?.meta_pixel_id||"").trim();const token=(await getSecret(admin,"meta_capi_access_token"))||String(body?.fallbackToken||"").trim();if(!pixelId||!token)return json({status:"not_configured"});
 const payload={data:[{event_name:eventName,event_time:Math.floor(Date.now()/1000),event_id:eventId,action_source:"website",event_source_url:body?.event_source_url?String(body.event_source_url).slice(0,2048):undefined,user_data:body?.user_data||{},custom_data:body?.custom_data||{}}]};
 const res=await fetch(`https://graph.facebook.com/${GRAPH_VERSION}/${pixelId}/events?access_token=${encodeURIComponent(token)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const meta=await res.json().catch(()=>({error:"invalid_meta_response"}));return json({status:res.ok?"sent":"error",meta},res.ok?200:502);
}
async function insights(admin:any,body:any){
 const {data:s,error}=await admin.from("store_settings").select("meta_ad_account_id").eq("id",1).maybeSingle();if(error)return json({configured:false,connected:false,error:error.message},500);
 const accountId=account(s?.meta_ad_account_id);const marketing=await getSecret(admin,"meta_marketing_access_token");const token=marketing||await getSecret(admin,"meta_capi_access_token")||String(body?.fallbackToken||"").trim();const period=String(body?.period||"30d");const preset=period==="7d"?"last_7d":period==="all"?"maximum":"last_30d";if(!accountId||!token)return json({configured:false,connected:false,reason:"missing_ad_account_or_marketing_token"});
 const url=new URL(`https://graph.facebook.com/${GRAPH_VERSION}/act_${accountId}/insights`);url.searchParams.set("fields","spend,impressions,clicks,actions,action_values,purchase_roas");url.searchParams.set("date_preset",preset);url.searchParams.set("level","account");url.searchParams.set("access_token",token);const res=await fetch(url,{cache:"no-store"});const data=await res.json().catch(()=>({}));if(!res.ok)return json({configured:true,connected:false,error:data?.error?.message||"Meta API error"},502);
 const row=data?.data?.[0]||{};const av=(list:unknown,re:RegExp)=>Array.isArray(list)?list.filter((x:any)=>re.test(String(x?.action_type||""))).reduce((n:number,x:any)=>n+Number(x?.value||0),0):0;const purchases=av(row.actions,/purchase/i);const purchaseValue=av(row.action_values,/purchase/i);const spend=Number(row.spend||0);return json({configured:true,connected:true,period,spend,impressions:Number(row.impressions||0),clicks:Number(row.clicks||0),purchases,purchaseValue,costPerPurchase:purchases>0?spend/purchases:0,roas:spend>0?purchaseValue/spend:0});
}
async function saveSecrets(supabase:any,body:any){const {data,isAdminError}=await supabase.rpc("is_admin").then((r:any)=>({data:r.data,isAdminError:r.error}));if(isAdminError||!isAdminError&&data!==true)return json({error:"forbidden"},403);for(const [name,value] of [["meta_capi_access_token",body?.capiAccessToken],["meta_marketing_access_token",body?.marketingAccessToken]] as const){if(value!==undefined){const {error}=await supabase.rpc("set_meta_runtime_secret",{p_name:name,p_value:String(value||"").trim()});if(error)return json({error:"No se pudo guardar uno de los tokens de Meta."},500);}}return json({ok:true});}
export default {fetch:withSupabase({auth:["user","publishable"]},async(req,ctx)=>{if(req.method!=="POST")return json({error:"method_not_allowed"},405);let body:any;try{body=await req.json()}catch{return json({error:"invalid_body"},400)}try{const action=String(body?.action||"");if(action==="save_secrets")return saveSecrets(ctx.supabase,body);if(action==="capi")return sendCapi(ctx.supabaseAdmin,body);if(action==="insights")return insights(ctx.supabaseAdmin,body);return json({error:"unknown_action"},400)}catch(e){console.error(e);return json({error:"meta_runtime_error"},500)}})};
