"use client";

import { useEffect, useRef } from "react";

/** Keeps Android/browser back inside the three checkout steps. */
export default function CheckoutHistory() {
  const currentStep = useRef(1);
  const handlingPop = useRef(false);

  useEffect(() => {
    const makeState = (step: number) => ({
      ...(window.history.state || {}),
      __dfCheckout: true,
      checkoutStep: step,
    });

    currentStep.current = 1;
    window.history.replaceState(makeState(1), "", window.location.href);

    const getButton = (pattern: RegExp) => Array.from(document.querySelectorAll("button"))
      .find((button) => pattern.test((button.textContent || "").trim())) as HTMLButtonElement | undefined;

    const onClickCapture = (event: MouseEvent) => {
      const element = event.target as HTMLElement | null;
      const button = element?.closest("button");
      if (!button) return;

      const label = (button.textContent || "").trim();

      // CONTINUAR creates the next real browser-history entry before React
      // changes its local step state.
      if (/continuar/i.test(label) && currentStep.current < 3) {
        const nextStep = currentStep.current + 1;
        currentStep.current = nextStep;
        window.history.pushState(makeState(nextStep), "", window.location.href);
        return;
      }

      // Do not convert the programmatic click generated by popstate into a
      // second history.back() call. React's existing onClick will set the step.
      if (/volver/i.test(label) && currentStep.current > 1 && !handlingPop.current) {
        event.preventDefault();
        event.stopPropagation();
        window.history.back();
      }
    };

    const onPopState = (event: PopStateEvent) => {
      const targetStep = Number(event.state?.checkoutStep || 0);
      if (!event.state?.__dfCheckout || !targetStep) return;
      if (targetStep >= currentStep.current) return;

      currentStep.current = targetStep;
      handlingPop.current = true;

      // The actual page already has a Volver button. Its React handler changes
      // the visible step; this avoids duplicating checkout business logic.
      const backButton = getButton(/volver/i);
      if (backButton) backButton.click();

      window.setTimeout(() => {
        handlingPop.current = false;
      }, 500);
    };

    document.addEventListener("click", onClickCapture, true);
    window.addEventListener("popstate", onPopState);

    return () => {
      document.removeEventListener("click", onClickCapture, true);
      window.removeEventListener("popstate", onPopState);
    };
  }, []);

  return null;
}
