"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {createClient} from "../../../lib/supabase/browser";

type Bank={id:string;bank:string;account_type:string|null;account_number:string|null;holder_name:string|null;document:string|null;alias:string|null;active:boolean};
type Tigo={id:string;phone:string;holder_name:string|null;document:string|null;active:boolean};
const emptyBank={bank:"",account_type:"Cuenta corriente",account_number:"",holder_name:"",document:"",alias:"",active:true};
const emptyTigo={phone:"",holder_name:"",document:"",active:true};
export default function Pagos(){
 const [banks,setBanks]=useState<Bank[]>([]),[tigos,setTigos]=useState<Tigo[]>([]),[bank,setBank]=useState<any>(emptyBank),[tigo,setTigo]=useState<any>(emptyTigo),[msg,setMsg]=useState(""),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);const s=createClient();const [b,t]=await Promise.all([s.from("bank_accounts").select("*").order("bank"),s.from("tigo_accounts").select("*").order("phone")]);setBanks(b.data||[]);setTigos(t.data||[]);setMsg(b.error?.message||t.error?.message||"");setLoading(false)}
 useEffect(()=>{load()},[]);
 async function addBank(e:React.FormEvent){e.preventDefault();setMsg("");const s=createClient();const {error}=await s.from("bank_accounts").insert(bank);if(error)setMsg(error.message);else{setBank(emptyBank);load()}}
 async function addTigo(e:React.FormEvent){e.preventDefault();setMsg("");const s=createClient();const {error}=await s.from("tigo_accounts").insert(tigo);if(error)setMsg(error.message);else{setTigo(emptyTigo);load()}}
 async function toggle(table:string,id:string,active:boolean){const s=createClient();const {error}=await s.from(table).update({active:!active}).eq("id",id);if(error)setMsg(error.message);else load()}
 async function remove(table:string,id:string){if(!confirm("¿Eliminar este dato de pago?"))return;const s=createClient();const {error}=await s.from(table).delete().eq("id",id);if(error)setMsg(error.message);else load()}
 return <section><div className="title"><div><small>ADMINISTRADOR</small><h1>Métodos de pago</h1></div><Link href="/admin">← Admin</Link></div>{msg&&<div className="panel">⚠️ {msg}</div>}
 <div className="panel"><h2>Cuentas bancarias</h2><p className="muted">Estos datos se mostrarán automáticamente en el checkout cuando el cliente elija Transferencia.</p><form className="product-form" onSubmit={addBank}><div className="twocol"><label>Banco*<input required value={bank.bank} onChange={e=>setBank({...bank,bank:e.target.value})}/></label><label>Tipo de cuenta<select value={bank.account_type} onChange={e=>setBank({...bank,account_type:e.target.value})}><option>Cuenta corriente</option><option>Cuenta ahorro</option></select></label><label>Número de cuenta*<input required value={bank.account_number} onChange={e=>setBank({...bank,account_number:e.target.value})}/></label><label>Titular*<input required value={bank.holder_name} onChange={e=>setBank({...bank,holder_name:e.target.value})}/></label><label>Cédula/RUC<input value={bank.document} onChange={e=>setBank({...bank,document:e.target.value})}/></label><label>Alias<input value={bank.alias} onChange={e=>setBank({...bank,alias:e.target.value})}/></label></div><button className="btn">+ Agregar cuenta</button></form>{!loading&&<div className="payment-list">{banks.map(x=><div className="panel payment-row" key={x.id}><div><b>{x.bank}</b> · {x.account_type}<br/>N.º {x.account_number} · {x.holder_name}{x.alias?` · Alias: ${x.alias}`:""}{x.document?` · CI/RUC: ${x.document}`:""}</div><div className="actions"><button className="btn secondary" onClick={()=>toggle("bank_accounts",x.id,x.active)}>{x.active?"Desactivar":"Activar"}</button><button className="link-btn" onClick={()=>remove("bank_accounts",x.id)}>Eliminar</button></div></div>)}</div>}</div>
 <div className="panel"><h2>Giro Tigo</h2><p className="muted">Estos datos se mostrarán automáticamente en el checkout cuando el cliente elija Giro Tigo.</p><form className="product-form" onSubmit={addTigo}><div className="twocol"><label>Celular*<input required value={tigo.phone} onChange={e=>setTigo({...tigo,phone:e.target.value})}/></label><label>Titular*<input required value={tigo.holder_name} onChange={e=>setTigo({...tigo,holder_name:e.target.value})}/></label><label>Cédula/RUC<input value={tigo.document} onChange={e=>setTigo({...tigo,document:e.target.value})}/></label></div><button className="btn">+ Agregar número</button></form>{!loading&&<div className="payment-list">{tigos.map(x=><div className="panel payment-row" key={x.id}><div><b>{x.phone}</b> · {x.holder_name}{x.document?` · CI/RUC: ${x.document}`:""}</div><div className="actions"><button className="btn secondary" onClick={()=>toggle("tigo_accounts",x.id,x.active)}>{x.active?"Desactivar":"Activar"}</button><button className="link-btn" onClick={()=>remove("tigo_accounts",x.id)}>Eliminar</button></div></div>)}</div>}</div>
 </section>
}
